### ISSUE TITLE
Unit test doesn't work on Release 0.1.1

### ISSUE THREAD

**Issue by nicolasStevenin** [go-warnings/warnings#1]
Hello !
Unit test doesn't work on Release 0.1.1

+ pushd /builddir/build/BUILD/warnings-0.1.1/_build/src/gopkg.in/warnings.v0/.
+ go test -compiler gc -ldflags ''
FAIL    gopkg.in/warnings.v0 [build failed]
# gopkg.in/warnings.v0_test
./warnings_test.go:11: undefined: List

Using Golang version  "golang-1.8.3-1.el7.x86_64"

Best regards
Nicolas

**Comment by speter** [comment]
Thanks for reporting. Fixed in v0.1.2.

**Comment by nicolasStevenin** [comment]
Thank you, it works !
